services:
  - type: web
    name: cpu-scheduler-backend
    env: python
    buildCommand: "cmake -DBUILD_GUI=OFF . && make SimulatorCLI && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    
    envVars:
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
    
    # Resource specifications
    plan: standard
    
    # Health check
    healthCheckPath: /
    healthCheckInterval: 30
    healthCheckTimeout: 5
